import './sass/style.scss';
import './blocks/section-container/script';
import './blocks/section-inner/script';
import './blocks/section-title/script';
import './blocks/tutoring-list/script';
import './blocks/testimonial-carousel/script';
import './blocks/call-to-action-list/script';
import './blocks/simple-call-to-action/script';
import './blocks/highlighter-arrow/script';